sources:
  - name: axis-auctions
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/65230/axisfi-auctions/0.0.4
    transforms:
      - autoPagination:
          validateSchema: true
documents:
  - ./queries/**/*.graphql
